apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rq1w3pf62-python
  janus-idp.io/tekton: rq1w3pf62-python
  backstage.io/kubernetes-id: rq1w3pf62-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rq1w3pf62-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
